"""
Malaysia Socioeconomic Portrait — Streamlit Dashboard
======================================================
Run: streamlit run app.py
Data: ../data/clean/  (generated by 00 → 01 notebooks)
"""

import streamlit as st
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import os

# ── Page config ───────────────────────────────────────────────
st.set_page_config(
    page_title="Malaysia Socioeconomic Portrait",
    page_icon="🇲🇾",
    layout="wide",
    initial_sidebar_state="expanded"
)

# ── Custom CSS ────────────────────────────────────────────────
st.markdown("""
<style>
    .main { background-color: #F8FAFC; }
    .block-container { padding-top: 1.5rem; padding-bottom: 1rem; }
    h1 { color: #1B3A6B; }
    h2 { color: #1B3A6B; border-bottom: 2px solid #0E7490; padding-bottom: 6px; }
    .stMetric {
        background: white; border-radius: 10px; padding: 12px;
        box-shadow: 0 1px 4px rgba(0,0,0,0.08);
    }
    section[data-testid="stSidebar"] { background-color: #1B3A6B; }
    section[data-testid="stSidebar"] * { color: white !important; }
</style>
""", unsafe_allow_html=True)

# ── Data loader ───────────────────────────────────────────────
CLEAN_DIR = '../data/clean'

@st.cache_data
def load(name):
    path = f'{CLEAN_DIR}/{name}.csv'
    if not os.path.exists(path):
        st.warning(f'Missing: {path} — run notebooks 00 and 01 first.')
        return None
    df = pd.read_csv(path)
    if 'year' not in df.columns and 'date' in df.columns:
        df['date'] = pd.to_datetime(df['date'], errors='coerce')
        df['year'] = df['date'].dt.year
    return df

pop_malaysia        = load('population_malaysia')
pop_state           = load('population_state')
fertility           = load('fertility')
fertility_state     = load('fertility_state')
births              = load('births_annual')
deaths              = load('deaths')
marriages           = load('marriages')
hh_income           = load('hh_income')
hh_income_state     = load('hh_income_state')
hh_inequality       = load('hh_inequality')
hh_inequality_state = load('hh_inequality_state')
hh_poverty          = load('hh_poverty')
hies_state          = load('hies_state')
cpi_inflation       = load('cpi_headline_inflation')

# ── Sidebar ───────────────────────────────────────────────────
with st.sidebar:
    st.markdown("## 🇲🇾 Malaysia")
    st.markdown("### Socioeconomic Portrait")
    st.markdown("---")
    page = st.selectbox(
        "Select Page",
        [
            "🏠 Overview — KPI Cards",
            "📊 Tema 1 — The Ageing Nation",
            "💰 Tema 2 — Income vs Inflation",
            "⚖️ Combined — Inequality Deep Dive",
        ]
    )
    st.markdown("---")
    st.markdown("**Data Source**")
    st.markdown("[OpenDOSM](https://open.dosm.gov.my/)")
    st.markdown("21 datasets | 2 themes")
    st.markdown("---")
    st.markdown("Built with Python + Plotly + Streamlit")


# ════════════════════════════════════════════════════════════════
# PAGE 0 — OVERVIEW KPI CARDS
# ════════════════════════════════════════════════════════════════
if page == "🏠 Overview — KPI Cards":
    st.title("🇲🇾 Malaysia Socioeconomic Portrait")
    st.markdown("**Data from OpenDOSM · Tema 1: Demography · Tema 2: Cost of Living**")
    st.markdown("---")

    # Compute KPIs safely
    pop_row  = pop_malaysia[(pop_malaysia['age']=='overall') & (pop_malaysia['sex']=='both') & (pop_malaysia['ethnicity']=='overall')].sort_values('year').iloc[-1]
    tfr_row  = fertility[fertility['age_group']=='tfr'].sort_values('year').iloc[-1]
    inc_row  = hh_income.sort_values('year').iloc[-1]
    gini_row = hh_inequality.sort_values('year').iloc[-1]
    pov_row  = hh_poverty.sort_values('year').iloc[-1]

    pop_mx  = pop_malaysia[(pop_malaysia['sex']=='both') & (pop_malaysia['ethnicity']=='overall') & (pop_malaysia['age']!='overall')].copy()
    young   = pop_mx[pop_mx['age'].isin(['0-4','5-9','10-14'])].groupby('year')['population'].sum()
    elderly = pop_mx[pop_mx['age'].isin(['60-64','65-69','70-74','75-79','80+'])].groupby('year')['population'].sum()
    ai      = (elderly / young * 100).sort_index().iloc[-1]

    cpi_ov  = cpi_inflation[(cpi_inflation['division']=='overall') & (cpi_inflation['inflation_yoy'].notna())]
    cpi_val = cpi_ov.groupby('year')['inflation_yoy'].mean().sort_index().iloc[-1]

    st.subheader("📈 Tema 1 — Demographic Indicators")
    c1, c2, c3, c4 = st.columns(4)
    c1.metric("🧑‍🤝‍🧑 Population",       f"{pop_row['population']:,.0f}k",      f"Year {int(pop_row['year'])}")
    c2.metric("👶 Fertility Rate (TFR)", f"{tfr_row['fertility_rate']:.2f}",    "⚠️ Below 2.1" if tfr_row['fertility_rate'] < 2.1 else "✅ Above 2.1")
    c3.metric("📉 Ageing Index",         f"{ai:.1f}",                            "⚠️ Ageing Nation" if ai >= 100 else "Approaching 100")
    c4.metric("📅 TFR Data Year",        str(int(tfr_row['year'])),             "Latest available")

    st.markdown("---")
    st.subheader("💰 Tema 2 — Economic Indicators")
    c5, c6, c7, c8 = st.columns(4)
    c5.metric("💵 Median Income",   f"RM {inc_row['income_median']:,.0f}/mo", f"Year {int(inc_row['year'])}")
    c6.metric("📊 CPI Inflation",   f"{cpi_val:+.1f}% YoY",                  "Latest annual avg")
    c7.metric("⚖️ Gini Coefficient",f"{gini_row['gini']:.3f}",               f"Year {int(gini_row['year'])}")
    c8.metric("🏠 Poverty Rate",    f"{pov_row['poverty_absolute']:.1f}%",    f"Year {int(pov_row['year'])}")

    st.markdown("---")
    st.info("👈 Use the sidebar to navigate to full chart pages.")


# ════════════════════════════════════════════════════════════════
# PAGE 1 — TEMA 1: THE AGEING NATION
# ════════════════════════════════════════════════════════════════
elif page == "📊 Tema 1 — The Ageing Nation":
    st.title("📊 Tema 1: The Ageing Nation")
    st.markdown("Malaysia's population is ageing rapidly — fewer children, more elderly.")
    st.markdown("---")

    # CHART 1 — Population Pyramid
    st.subheader("Chart 1 — Population Pyramid (Animated)")
    pyramid = pop_malaysia[
        (pop_malaysia['ethnicity'] == 'overall') &
        (pop_malaysia['sex'].isin(['male', 'female'])) &
        (~pop_malaysia['age'].isin(['overall', '70+']))
    ].copy()
    age_order = ['0-4','5-9','10-14','15-19','20-24','25-29','30-34',
                 '35-39','40-44','45-49','50-54','55-59','60-64',
                 '65-69','70-74','75-79','80+']
    age_order = [a for a in age_order if a in pyramid['age'].unique()]
    pyramid   = pyramid[pyramid['age'].isin(age_order)].copy()
    pyramid['pop_plot'] = pyramid.apply(
        lambda r: -r['population'] if r['sex'] == 'male' else r['population'], axis=1
    )
    pyramid['age'] = pd.Categorical(pyramid['age'], categories=age_order, ordered=True)
    pyramid = pyramid.sort_values(['year', 'age'])

    fig1 = px.bar(
        pyramid, x='pop_plot', y='age', color='sex',
        animation_frame='year', orientation='h',
        color_discrete_map={'male': '#0E7490', 'female': '#BE185D'},
        title='Chart 1: Malaysia Population Pyramid — Watch Malaysia Age Over Time!',
        labels={'pop_plot': 'Population (thousands)', 'age': 'Age Group'},
        template='plotly_white', height=550,
        category_orders={'age': age_order}
    )
    fig1.update_layout(
        bargap=0.08,
        xaxis_title='← Male (thousands)          Female (thousands) →',
        legend_title='Sex'
    )
    st.plotly_chart(fig1, use_container_width=True)
    st.info("💡 **Insight:** Drag the year slider — the pyramid base gets narrower every decade. Fewer young people = ageing nation.")

    st.markdown("---")

    # CHART 2 + CHART 3 side by side
    col_a, col_b = st.columns(2)

    with col_a:
        st.subheader("Chart 2 — Total Fertility Rate (TFR)")
        tfr      = fertility[fertility['age_group'] == 'tfr'].sort_values('year').copy()
        latest   = tfr.iloc[-1]
        below_21 = tfr[tfr['fertility_rate'] < 2.1]
        first_below_yr = int(below_21.iloc[0]['year']) if len(below_21) > 0 else None

        fig2 = go.Figure()
        fig2.add_trace(go.Scatter(
            x=tfr['year'], y=tfr['fertility_rate'],
            mode='lines+markers', name='TFR',
            line=dict(color='#B45309', width=3), marker=dict(size=5),
            hovertemplate='%{x}: <b>%{y:.2f}</b> children/woman<extra></extra>'
        ))
        fig2.add_hline(y=2.1, line_dash='dash', line_color='#DC2626', line_width=2,
                       annotation_text='Replacement Level (2.1)',
                       annotation_position='top right', annotation_font_color='#DC2626')
        if first_below_yr:
            fig2.add_annotation(
                x=first_below_yr, y=2.1,
                text=f'Crossed below 2.1 in {first_below_yr}',
                showarrow=True, arrowhead=2, ax=50, ay=-30,
                font=dict(size=10, color='#DC2626'),
                bgcolor='rgba(254,242,242,0.9)', bordercolor='#DC2626'
            )
        fig2.update_layout(
            title=f'TFR {int(tfr["year"].min())}–{int(tfr["year"].max())}',
            xaxis_title='Year', yaxis_title='Children per Woman',
            template='plotly_white', height=400, hovermode='x unified'
        )
        st.plotly_chart(fig2, use_container_width=True)
        st.info(f"💡 TFR = **{latest['fertility_rate']:.2f}** ({int(latest['year'])}) — below the 2.1 replacement level.")

    with col_b:
        st.subheader("Chart 3 — Births vs Deaths")
        b = births.sort_values('year').copy()
        d = deaths.sort_values('year').copy()

        fig3 = go.Figure()
        fig3.add_trace(go.Scatter(
            x=b['year'], y=b['abs'], mode='lines+markers', name='Live Births',
            line=dict(color='#15803D', width=2.5), marker=dict(size=5),
            hovertemplate='%{x}: <b>%{y:,.0f}</b> births<extra></extra>'
        ))
        fig3.add_trace(go.Scatter(
            x=d['year'], y=d['abs'], mode='lines+markers', name='Deaths',
            line=dict(color='#B91C1C', width=2.5), marker=dict(size=5),
            hovertemplate='%{x}: <b>%{y:,.0f}</b> deaths<extra></extra>'
        ))
        common = sorted(set(b['year']) & set(d['year']))
        if common:
            b_c = b[b['year'].isin(common)].sort_values('year')
            d_c = d[d['year'].isin(common)].sort_values('year')
            fig3.add_trace(go.Scatter(
                x=list(b_c['year']) + list(b_c['year'])[::-1],
                y=list(b_c['abs'])  + list(d_c['abs'])[::-1],
                fill='toself', fillcolor='rgba(21,128,61,0.08)',
                line=dict(color='rgba(0,0,0,0)'),
                showlegend=False, hoverinfo='skip'
            ))
        fig3.update_layout(
            title='Births vs Deaths — Natural Growth Slowing',
            xaxis_title='Year', yaxis_title='Count',
            template='plotly_white', height=400, hovermode='x unified'
        )
        st.plotly_chart(fig3, use_container_width=True)
        st.info("💡 The gap between births and deaths is **narrowing** — natural population growth is slowing down.")

    st.markdown("---")

    # CHART 4 — TFR by State
    st.subheader("Chart 4 — Fertility Rate by State (Latest Year)")
    tfr_st = fertility_state[fertility_state['age_group'] == 'tfr'].copy()
    for col in ['sex', 'ethnicity']:
        if col in tfr_st.columns:
            vals = tfr_st[col].unique()
            if 'both' in vals:     tfr_st = tfr_st[tfr_st[col] == 'both']
            elif 'overall' in vals: tfr_st = tfr_st[tfr_st[col] == 'overall']
    latest_yr  = int(tfr_st['year'].max())
    tfr_latest = (tfr_st[tfr_st['year'] == latest_yr]
                  .groupby('state', as_index=False)['fertility_rate'].mean()
                  .sort_values('fertility_rate', ascending=True))
    nat_avg    = tfr_latest['fertility_rate'].mean()

    fig4 = go.Figure()
    fig4.add_trace(go.Bar(
        x=tfr_latest['fertility_rate'], y=tfr_latest['state'],
        orientation='h',
        marker_color=['#B91C1C' if v < 2.1 else '#15803D' for v in tfr_latest['fertility_rate']],
        text=[f'{v:.2f}' for v in tfr_latest['fertility_rate']],
        textposition='outside',
        hovertemplate='<b>%{y}</b>: %{x:.2f} children/woman<extra></extra>'
    ))
    fig4.add_vline(x=2.1, line_dash='dot', line_color='#D97706', line_width=2,
                   annotation_text='2.1 Replacement', annotation_position='top right')
    fig4.add_vline(x=nat_avg, line_dash='dash', line_color='#94A3B8', line_width=1.5,
                   annotation_text=f'Avg {nat_avg:.2f}', annotation_position='bottom right')
    fig4.update_layout(
        title=f'Fertility Rate by State ({latest_yr}) — 🔴 Below 2.1 / 🟢 Above 2.1',
        xaxis_title='Children per Woman',
        template='plotly_white', height=520, margin=dict(l=150, r=120)
    )
    st.plotly_chart(fig4, use_container_width=True)

    pct_below = len(tfr_latest[tfr_latest['fertility_rate'] < 2.1]) / len(tfr_latest) * 100
    st.info(f"💡 **{pct_below:.0f}%** of states are BELOW the 2.1 replacement level in {latest_yr}.")

    st.markdown("---")

    # CHART 5 — Ageing Index
    st.subheader("Chart 5 — Ageing Index (Derived Metric)")
    pop_mx  = pop_malaysia[(pop_malaysia['sex']=='both') & (pop_malaysia['ethnicity']=='overall') & (pop_malaysia['age']!='overall')].copy()
    young_s = pop_mx[pop_mx['age'].isin(['0-4','5-9','10-14'])].groupby('year')['population'].sum().reset_index()
    eld_s   = pop_mx[pop_mx['age'].isin(['60-64','65-69','70-74','75-79','80+'])].groupby('year')['population'].sum().reset_index()
    ageing  = pd.merge(young_s, eld_s, on='year', suffixes=('_young','_elderly'))
    ageing['ageing_index'] = (ageing['population_elderly'] / ageing['population_young']) * 100
    ageing  = ageing.sort_values('year').reset_index(drop=True)
    latest_ai = ageing.iloc[-1]
    crossed   = ageing[ageing['ageing_index'] >= 100]
    cross_yr  = int(crossed.iloc[0]['year']) if len(crossed) > 0 else None

    fig5 = go.Figure()
    fig5.add_trace(go.Scatter(
        x=ageing['year'], y=ageing['ageing_index'],
        mode='lines+markers', line=dict(color='#7C3AED', width=3),
        marker=dict(size=6, color=['#B91C1C' if v >= 100 else '#7C3AED' for v in ageing['ageing_index']]),
        fill='tozeroy', fillcolor='rgba(124,58,237,0.07)',
        name='Ageing Index',
        hovertemplate='%{x}: Ageing Index = <b>%{y:.1f}</b><extra></extra>'
    ))
    fig5.add_hline(y=100, line_dash='dash', line_color='#DC2626', line_width=2,
                   annotation_text='Index 100 = Equal elderly & children',
                   annotation_position='bottom right', annotation_font_color='#DC2626')
    if cross_yr:
        fig5.add_vrect(x0=cross_yr, x1=int(ageing['year'].max()),
                       fillcolor='rgba(239,68,68,0.04)', layer='below', line_width=0)
    fig5.add_annotation(
        x=latest_ai['year'], y=latest_ai['ageing_index'],
        text=f'<b>{int(latest_ai["year"])}: {latest_ai["ageing_index"]:.1f}</b>',
        showarrow=True, arrowhead=2, ax=45, ay=-40,
        font=dict(color='#7C3AED', size=12),
        bgcolor='rgba(237,233,254,0.9)', bordercolor='#7C3AED'
    )
    fig5.update_layout(
        title='Chart 5: Ageing Index = (Pop 60+) / (Pop 0–14) × 100  [Derived Metric]',
        xaxis_title='Year', yaxis_title='Ageing Index',
        template='plotly_white', height=440, hovermode='x unified'
    )
    st.plotly_chart(fig5, use_container_width=True)
    msg = f"⚠️ Ageing Index = **{latest_ai['ageing_index']:.1f}** — Malaysia has MORE elderly than children!" if latest_ai['ageing_index'] >= 100 else f"💡 Ageing Index = **{latest_ai['ageing_index']:.1f}** — approaching the aged-nation threshold of 100."
    st.info(msg)


# ════════════════════════════════════════════════════════════════
# PAGE 2 — TEMA 2: INCOME vs INFLATION
# ════════════════════════════════════════════════════════════════
elif page == "💰 Tema 2 — Income vs Inflation":
    st.title("💰 Tema 2: Income vs Inflation")
    st.markdown("Is Malaysia's rising income keeping pace with the cost of living?")
    st.markdown("---")

    # CPI annual aggregation (reused across charts)
    cpi_overall = cpi_inflation[(cpi_inflation['division']=='overall') & (cpi_inflation['inflation_yoy'].notna())].copy()
    cpi_yr      = cpi_overall.groupby('year')['inflation_yoy'].mean().reset_index()
    cpi_yr.columns = ['year', 'cpi_yoy']
    income = hh_income.sort_values('year').copy()

    # CHART 6 — HERO
    st.subheader("⭐ Chart 6 — HERO: Median Income vs CPI Inflation")
    fig6 = make_subplots(specs=[[{'secondary_y': True}]])
    fig6.add_trace(go.Scatter(
        x=income['year'], y=income['income_median'],
        mode='lines+markers', name='Median Income (RM/month)',
        line=dict(color='#15803D', width=3.5), marker=dict(size=8),
        hovertemplate='%{x}: <b>RM %{y:,.0f}</b>/month<extra></extra>'
    ), secondary_y=False)
    fig6.add_trace(go.Scatter(
        x=income['year'], y=income['income_mean'],
        mode='lines+markers', name='Mean Income (RM/month)',
        line=dict(color='#0E7490', width=2, dash='dot'), marker=dict(size=5),
        hovertemplate='%{x}: RM %{y:,.0f}<extra></extra>'
    ), secondary_y=False)
    fig6.add_trace(go.Scatter(
        x=cpi_yr['year'], y=cpi_yr['cpi_yoy'],
        mode='lines+markers', name='CPI Inflation % (YoY)',
        line=dict(color='#B91C1C', width=2.5, dash='dash'),
        marker=dict(size=7, symbol='diamond'),
        hovertemplate='%{x}: <b>%{y:.1f}%</b> inflation<extra></extra>'
    ), secondary_y=True)

    first_inc, last_inc = income.iloc[0], income.iloc[-1]
    for row, ax, ay in [(first_inc, 30, -30), (last_inc, -40, -35)]:
        fig6.add_annotation(x=row['year'], y=row['income_median'],
            text=f'RM {row["income_median"]:,.0f}', showarrow=True,
            arrowhead=1, ax=ax, ay=ay,
            font=dict(size=10, color='#15803D'), bgcolor='rgba(240,253,244,0.9)')

    fig6.update_layout(
        title='⭐ HERO: Median Income vs CPI Inflation — Does Real Income Grow?',
        template='plotly_white', height=500, hovermode='x unified',
        legend=dict(x=0.01, y=0.99, bgcolor='rgba(255,255,255,0.9)')
    )
    fig6.update_yaxes(title_text='Monthly Household Income (RM)',
                      secondary_y=False, tickprefix='RM ', tickformat=',')
    fig6.update_yaxes(title_text='CPI Inflation Rate (% YoY)',
                      secondary_y=True, ticksuffix='%')
    st.plotly_chart(fig6, use_container_width=True)

    growth = ((last_inc['income_median'] / first_inc['income_median']) - 1) * 100
    st.info(f"💡 Median income rose **RM {first_inc['income_median']:,.0f} → RM {last_inc['income_median']:,.0f}** (+{growth:.0f}%) — but inflation spikes erode real gains.")

    st.markdown("---")

    # CHART 7 — Real Purchasing Power
    st.subheader("Chart 7 — Real Purchasing Power (Derived Metric)")
    income_s = income.copy()
    income_s['income_growth_pct'] = income_s['income_median'].pct_change() * 100
    real = pd.merge(
        income_s[['year','income_median','income_growth_pct']],
        cpi_yr, on='year', how='inner'
    ).dropna()
    real['real_growth'] = real['income_growth_pct'] - real['cpi_yoy']
    real = real.sort_values('year').reset_index(drop=True)

    fig7 = go.Figure()
    fig7.add_trace(go.Bar(
        x=real['year'], y=real['real_growth'],
        marker_color=['#15803D' if v >= 0 else '#B91C1C' for v in real['real_growth']],
        text=[f'{v:+.1f}%' for v in real['real_growth'].round(1)],
        textposition='outside', textfont=dict(size=10),
        name='Real Wage Growth',
        hovertemplate='%{x}: Real growth = <b>%{y:+.1f}%</b><extra></extra>',
        width=0.6
    ))
    fig7.add_hline(y=0, line_color='#374151', line_width=2)
    fig7.update_layout(
        title='Chart 7: Real Purchasing Power = Income Growth % − CPI Inflation %<br>'
              '<sup>🟢 Green = income outpaced inflation  |  🔴 Red = inflation ate into income</sup>',
        xaxis_title='Year', yaxis_title='Real Growth (%)',
        yaxis_ticksuffix='%', xaxis=dict(type='category'),
        template='plotly_white', height=420
    )
    st.plotly_chart(fig7, use_container_width=True)
    bad  = real[real['real_growth'] < 0]['year'].astype(int).tolist()
    good = real[real['real_growth'] >= 0]['year'].astype(int).tolist()
    st.info(f"💡 Years income **beat** inflation: {good} | Years inflation **won**: {bad}")

    st.markdown("---")

    col_c, col_d = st.columns(2)

    # CHART 8 — Income by State
    with col_c:
        st.subheader("Chart 8 — Income by State")
        latest_yr  = int(hh_income_state['year'].max())
        inc_state  = hh_income_state[hh_income_state['year']==latest_yr].dropna(subset=['income_median']).sort_values('income_median', ascending=True).copy()
        nat_vals   = hh_income[hh_income['year']==latest_yr]['income_median'].values
        nat_median = nat_vals[0] if len(nat_vals) > 0 else inc_state['income_median'].median()

        fig8 = go.Figure(go.Bar(
            x=inc_state['income_median'], y=inc_state['state'],
            orientation='h',
            marker_color=['#15803D' if v >= nat_median else '#B91C1C' for v in inc_state['income_median']],
            text=[f'RM {v:,.0f}' for v in inc_state['income_median']],
            textposition='outside', textfont=dict(size=9),
            hovertemplate='<b>%{y}</b>: RM %{x:,.0f}/month<extra></extra>'
        ))
        fig8.add_vline(x=nat_median, line_dash='dash', line_color='#7C3AED', line_width=2,
                       annotation=dict(text=f'National Median RM {nat_median:,.0f}',
                                       font=dict(size=9, color='#7C3AED')),
                       annotation_position='top')
        fig8.update_layout(
            title=f'Income by State ({latest_yr}) — 🟢 Above / 🔴 Below National Median',
            xaxis=dict(tickprefix='RM ', tickformat=',',
                       range=[0, inc_state['income_median'].max() * 1.3]),
            template='plotly_white', height=520, margin=dict(l=160, r=100)
        )
        st.plotly_chart(fig8, use_container_width=True)

    # CHART 10 — Poverty Trend
    with col_d:
        st.subheader("Chart 10 — Poverty Rate Trend")
        poverty_c = hh_poverty.sort_values('year').copy()
        hardcore  = poverty_c.dropna(subset=['poverty_hardcore']).copy()
        first_pov, last_pov = poverty_c.iloc[0], poverty_c.iloc[-1]

        fig10 = go.Figure()
        fig10.add_trace(go.Scatter(
            x=poverty_c['year'], y=poverty_c['poverty_absolute'],
            mode='lines+markers', name='Absolute Poverty (%)',
            line=dict(color='#B45309', width=3), marker=dict(size=8),
            fill='tozeroy', fillcolor='rgba(180,83,9,0.07)',
            hovertemplate='%{x}: <b>%{y:.1f}%</b><extra></extra>'
        ))
        if len(hardcore) > 0:
            fig10.add_trace(go.Scatter(
                x=hardcore['year'], y=hardcore['poverty_hardcore'],
                mode='lines+markers', name='Hardcore Poverty (%)',
                line=dict(color='#B91C1C', width=2, dash='dot'), marker=dict(size=6),
                hovertemplate='%{x}: <b>%{y:.1f}%</b> hardcore<extra></extra>'
            ))
        fig10.add_annotation(x=first_pov['year'], y=first_pov['poverty_absolute'],
            text=f'<b>{first_pov["poverty_absolute"]:.0f}%</b>', showarrow=True,
            arrowhead=2, ax=35, ay=-30, bgcolor='#FEF3C7', bordercolor='#B45309', font_size=11)
        fig10.add_annotation(x=last_pov['year'], y=last_pov['poverty_absolute'],
            text=f'<b>{last_pov["poverty_absolute"]:.1f}%</b>', showarrow=True,
            arrowhead=2, ax=-40, ay=-35, bgcolor='#DCFCE7', bordercolor='#15803D', font_size=11)
        fig10.update_layout(
            title=f'Poverty Rate — {first_pov["poverty_absolute"]:.0f}% → {last_pov["poverty_absolute"]:.1f}% 🎉',
            xaxis_title='Year', yaxis_title='Poverty Rate (%)', yaxis_ticksuffix='%',
            template='plotly_white', height=520, legend=dict(x=0.6, y=0.99)
        )
        st.plotly_chart(fig10, use_container_width=True)

    st.markdown("---")

    # CHART 11 — CPI by Category
    st.subheader("Chart 11 — CPI Inflation by Category")
    division_map = {
        'overall':'Overall CPI', '01':'Food & Non-Alcoholic Beverages',
        '04':'Housing, Water & Energy', '07':'Transport',
        '06':'Health', '10':'Education'
    }
    color_map = {
        'Overall CPI':'#1B3A6B', 'Food & Non-Alcoholic Beverages':'#B91C1C',
        'Housing, Water & Energy':'#0E7490', 'Transport':'#D97706',
        'Health':'#7C3AED', 'Education':'#065F46'
    }
    cpi_c = cpi_inflation[cpi_inflation['division'].isin(division_map.keys())].copy()
    cpi_c['div_name'] = cpi_c['division'].map(division_map)
    cpi_c = cpi_c.dropna(subset=['div_name', 'inflation_yoy'])
    cpi_ann = cpi_c.groupby(['year','div_name'])['inflation_yoy'].mean().reset_index()

    all_cats = sorted(cpi_ann['div_name'].unique().tolist())
    selected = st.multiselect("Filter categories:", all_cats, default=all_cats)
    cpi_filt = cpi_ann[cpi_ann['div_name'].isin(selected)]

    fig11 = go.Figure()
    for div in cpi_filt['div_name'].unique():
        df_d = cpi_filt[cpi_filt['div_name'] == div].sort_values('year')
        fig11.add_trace(go.Scatter(
            x=df_d['year'], y=df_d['inflation_yoy'],
            mode='lines+markers', name=div,
            line=dict(width=3 if div=='Overall CPI' else 2, color=color_map.get(div, '#94A3B8')),
            marker=dict(size=5),
            hovertemplate=div + '<br>%{x}: <b>%{y:.1f}%</b><extra></extra>'
        ))
    fig11.add_hline(y=0, line_color='#9CA3AF', line_width=1)
    fig11.update_layout(
        title='CPI Inflation by Category (% YoY) — Food Hits Hardest',
        xaxis_title='Year', yaxis_title='Inflation Rate (% YoY)', yaxis_ticksuffix='%',
        template='plotly_white', height=450, hovermode='x unified',
        legend=dict(x=0.01, y=0.99, bgcolor='rgba(255,255,255,0.9)')
    )
    st.plotly_chart(fig11, use_container_width=True)
    st.info("💡 Food & beverage inflation hits B40 households hardest — they spend the largest income share on food.")


# ════════════════════════════════════════════════════════════════
# PAGE 3 — COMBINED: INEQUALITY DEEP DIVE
# ════════════════════════════════════════════════════════════════
elif page == "⚖️ Combined — Inequality Deep Dive":
    st.title("⚖️ Combined: Inequality Deep Dive")
    st.markdown("Connecting demography, income, and inequality across all Malaysian states.")
    st.markdown("---")

    # CHART 9 — Gini Heatmap
    st.subheader("Chart 9 — Gini Coefficient Heatmap (State × Year)")
    gini_pivot = hh_inequality_state.pivot_table(index='state', columns='year', values='gini')
    latest_col = gini_pivot.columns[-1]
    gini_pivot = gini_pivot.sort_values(latest_col, ascending=False)
    text_vals  = [
        [f'{v:.3f}' if not np.isnan(v) else '' for v in row]
        for row in gini_pivot.values
    ]

    fig9 = go.Figure(go.Heatmap(
        z=gini_pivot.values,
        x=[str(int(c)) for c in gini_pivot.columns],
        y=gini_pivot.index.tolist(),
        colorscale='RdYlGn_r', zmin=0.30, zmax=0.55,
        hoverongaps=False,
        hovertemplate='<b>%{y}</b><br>Year: %{x}<br>Gini: <b>%{z:.3f}</b><extra></extra>',
        colorbar=dict(title=dict(text='Gini', side='right'), len=0.85),
        text=text_vals, texttemplate='%{text}',
        textfont=dict(size=9, color='#1F2937')
    ))
    fig9.update_layout(
        title='Chart 9: Gini Heatmap — 🔴 High Inequality  |  🟢 More Equal  |  Hover for exact values',
        xaxis_title='Year', yaxis_title='State',
        template='plotly_white', height=580, margin=dict(l=180)
    )
    st.plotly_chart(fig9, use_container_width=True)
    most_unequal  = gini_pivot[latest_col].idxmax()
    least_unequal = gini_pivot[latest_col].idxmin()
    st.info(f"💡 Most unequal: **{most_unequal}** (Gini = {gini_pivot.loc[most_unequal, latest_col]:.3f}) | Most equal: **{least_unequal}** (Gini = {gini_pivot.loc[least_unequal, latest_col]:.3f})")

    st.markdown("---")

    # CHART 12 — Bubble Chart
    st.subheader("Chart 12 — Bubble Chart: Income vs Inequality vs Population")
    hies_yr   = int(hies_state['year'].max())
    hies_data = hies_state[hies_state['year'] == hies_yr].copy()

    pop_st = pop_state[(pop_state['sex']=='both') & (pop_state['ethnicity']=='overall') & (pop_state['age']=='overall')].copy()
    if len(pop_st) == 0:
        pop_st = pop_state[(pop_state['sex']=='both') & (pop_state['age']=='overall')].copy()
    if len(pop_st) > 0:
        pop_yr       = int(pop_st['year'].max())
        pop_by_state = pop_st[pop_st['year']==pop_yr][['state','population']].copy()
        bubble       = pd.merge(hies_data, pop_by_state, on='state', how='left')
    else:
        bubble = hies_data.copy()
        bubble['population'] = np.nan

    bubble = bubble.dropna(subset=['income_median', 'gini'])
    if 'population' in bubble.columns and bubble['population'].notna().sum() >= 3:
        bubble      = bubble.dropna(subset=['population'])
        bubble_size = 'population'
        size_label  = 'Population (thousands)'
    elif 'expenditure_mean' in bubble.columns and bubble['expenditure_mean'].notna().sum() >= 3:
        bubble_size = 'expenditure_mean'
        size_label  = 'Mean Expenditure (RM/month)'
    else:
        bubble_size = 'income_median'
        size_label  = 'Median Income (RM/month)'

    fig12 = px.scatter(
        bubble, x='income_median', y='gini',
        size=bubble_size, color='state',
        hover_name='state', text='state', size_max=70,
        labels={
            'income_median': 'Median Household Income (RM/month)',
            'gini': 'Gini Coefficient (↑ = More Unequal)',
            bubble_size: size_label
        },
        title=f'Chart 12: Income vs Inequality by State ({hies_yr}) — X=Income | Y=Gini | Size={size_label}',
        template='plotly_white', height=580
    )
    fig12.update_traces(
        textposition='top center',
        textfont=dict(size=9, color='#374151'),
        marker=dict(opacity=0.82, line=dict(width=1.5, color='white'))
    )
    fig12.update_layout(
        xaxis=dict(tickprefix='RM ', tickformat=','),
        showlegend=False, title_font_size=13
    )
    st.plotly_chart(fig12, use_container_width=True)
    richest      = bubble.loc[bubble['income_median'].idxmax()]
    most_unequal = bubble.loc[bubble['gini'].idxmax()]
    st.info(f"💡 Highest income: **{richest['state']}** (RM {richest['income_median']:,.0f}) | Most unequal: **{most_unequal['state']}** (Gini = {most_unequal['gini']:.3f}). High income ≠ low inequality.")

    st.markdown("---")

    # FINAL STORY
    st.subheader("📖 The Full Story — So What Does This Mean?")
    latest_income = hh_income.sort_values('year').iloc[-1]
    first_income  = hh_income.sort_values('year').iloc[0]
    latest_gini   = hh_inequality.sort_values('year').iloc[-1]
    first_gini    = hh_inequality.sort_values('year').iloc[0]
    latest_pov    = hh_poverty.sort_values('year').iloc[-1]
    first_pov     = hh_poverty.sort_values('year').iloc[0]
    latest_tfr    = fertility[fertility['age_group']=='tfr'].sort_values('year').iloc[-1]
    pop_mx2       = pop_malaysia[(pop_malaysia['sex']=='both') & (pop_malaysia['ethnicity']=='overall') & (pop_malaysia['age']!='overall')].copy()
    y2 = pop_mx2[pop_mx2['age'].isin(['0-4','5-9','10-14'])].groupby('year')['population'].sum()
    e2 = pop_mx2[pop_mx2['age'].isin(['60-64','65-69','70-74','75-79','80+'])].groupby('year')['population'].sum()
    ai_latest = (e2 / y2 * 100).sort_index().iloc[-1]

    income_growth = ((latest_income['income_median'] / first_income['income_median']) - 1) * 100
    gini_improved = latest_gini['gini'] < first_gini['gini']
    pov_drop      = first_pov['poverty_absolute'] - latest_pov['poverty_absolute']

    col1, col2 = st.columns(2)
    with col1:
        st.markdown("### 🏙 Tema 1 Findings")
        st.markdown(f"""
- **TFR:** {latest_tfr['fertility_rate']:.2f} — {'⚠️ BELOW' if latest_tfr['fertility_rate'] < 2.1 else '✅ Above'} replacement level (2.1)
- **Ageing Index:** {ai_latest:.1f} — {'officially ageing nation' if ai_latest >= 100 else 'approaching aged status'}
- **Key risk:** Fewer workers supporting more retirees → pension & healthcare pressure
        """)
    with col2:
        st.markdown("### 💰 Tema 2 Findings")
        st.markdown(f"""
- **Income growth:** RM {first_income['income_median']:,.0f} → RM {latest_income['income_median']:,.0f} (+{income_growth:.0f}%)
- **Gini:** {first_gini['gini']:.3f} → {latest_gini['gini']:.3f} ({'✅ Improved' if gini_improved else '⚠️ Worsened'})
- **Poverty:** {first_pov['poverty_absolute']:.0f}% → {latest_pov['poverty_absolute']:.1f}% (−{pov_drop:.1f}pp 🎉)
- **Key risk:** Inflation spikes erode real income gains, especially for B40
        """)